#!/usr/bin/env python3

# Copyright (c) 2022, Cedric Velandres
# SPDX-License-Identifier: MIT

"""
Generate root kconfig that links all specified kconfig files
"""

KCONFIG_ROOT_HEADER="# AUTOGENERATED FILE. DO NOT MODIFY "
KCONFIG_DEFAULT_MAINMENU="Kconfig Project Configuration"

import argparse
import logging
import re
import os
from pathlib import Path

class KconfigMerge:
    def __init__(self, title: str,
                 kconfig_root: str,
                 srctree: str, 
                 list_sources: bool = True) -> None:
        self.title = title
        self.kconfig_root = Path(kconfig_root)
        self.sources = []
        self.root_dir = self.kconfig_root.parent
        self.common_dir = ""
        self.srctree = Path(srctree)
        self.kconfig_sources = {}
        self.logger = logging.getLogger("KconfigMerge")
        self.headers = ["# AUTOGENERATED FILE. DO NOT MODIFY"]
        self.recreate = False
        self.list_sources = list_sources

        # precreate root dir
        self.root_dir.mkdir(parents=True, exist_ok=True)

    def _get_common_relpath(self, source_path: Path) -> Path:
        """
        Returns the relative source path of input path with respect to common path of all sources
        Used for recreating the kconfig tree with adjusted source paths
        """
        return source_path.relative_to(self.common_dir)

    def _get_root_relpath(self, source_path: Path) -> Path:
        """
        Returns the relative source path of input path with respect to parent path of output kconfig root
        Also creates directories for the path
        """
        root_relpath = self.root_dir / self._get_common_relpath(source_path)
        if self.recreate: root_relpath.parent.mkdir(parents=True, exist_ok=True)
        return root_relpath

    def _get_srctree_relpath(self, source_path: Path) -> Path:
        """
        Returns the relative source path of input path with respect to srctree
        For non-recreate mode, all source paths are relative to srctree
        """
        return source_path.relative_to(self.srctree)

    def _lookup_source(self, parent, source_path: str) -> str:
        """
        Recurse search for a possible match of a sourced path given the parent kconfig file
        """
        for depth in range(len(Path(parent).parents)):
            parent_dir = Path(parent).parents[depth]
            candidate_path = parent_dir / source_path
            if candidate_path.exists():
                return candidate_path.absolute()
        return None

    def _parse_kconfig(self, parent, kconfig_source: Path) -> None:
        kconfig_common_relpath = self._get_common_relpath(kconfig_source)
        kconfig_root_relpath = self._get_root_relpath(kconfig_source)

        self.logger.debug(f"{'-' * 32}")
        self.logger.debug(f"source:          {kconfig_source}")
        self.logger.debug(f"common_relpath:  {kconfig_common_relpath}")
        self.logger.debug(f"root_relpath:    {kconfig_root_relpath}")

        # store parsed kconfig sources and destination kconfig file
        self.kconfig_sources[kconfig_source] = kconfig_root_relpath
        f_source_calls = []

        with open(kconfig_source, 'r') as f_source:
            if self.recreate: f_source_recreate = open(kconfig_root_relpath, 'w')
            for linenum, f_source_line in enumerate(f_source):
                match = re.match(r"^([r]?source)\s*\"([^\"]*)\"", f_source_line)
                if match:
                    source_token = match.group(1)
                    source_dir = match.group(2)

                    # absolute path to source arg
                    if source_token == "rsource":
                        source_abspath = Path(kconfig_source).parent / source_dir
                    else:
                        source_abspath = self._lookup_source(kconfig_source, source_dir)
                        if source_abspath is None:
                            raise FileNotFoundError(f"Could not find source file: {source_dir} in {parent}")

                    if self.recreate:
                        # Convert source arg relative to src tree in recreate mode
                        source_root_relpath = self._get_root_relpath(source_abspath)
                        source_arg = self._get_srctree_relpath(source_root_relpath)
                        self.logger.debug(f"source:          {source_dir} -> {source_arg}")
                        f_source_recreate.write(f"source \"{source_arg}\"\n")

                    f_source_calls.append((linenum, f_source_line, source_token, source_abspath))

                else:
                    if self.recreate:
                        f_source_recreate.write(f"{f_source_line}")
            if self.recreate: f_source_recreate.close()


        # For each source calls, parse the source and update the source path in the parent kconfig file
        for linenum, f_source_line, source_token, source_dir in f_source_calls:
            self._parse_kconfig(kconfig_source, source_dir)

    def import_sources(self, sources: list):
        """
        Imports a set of kconfig files to generate a tree of kconfig with adjusted
        source paths wre to the common dir of all kconfig paths
        """
        if(len(sources) > 1):
            self.common_dir = Path(os.path.commonpath(sources)).parent
            self.recreate = True # force when given multiroot sources
        else:
            # This really isn't a nice way to to do this :(
            self.common_dir = os.path.abspath(os.path.dirname(os.path.join(sources[0], "../../..")))

        self.logger.debug(f"root_dir:   {self.root_dir}")
        self.logger.debug(f"common_dir: {self.common_dir}")
        self.logger.debug(f"srctree:    {self.srctree}")

        with open(self.kconfig_root, 'w') as kconfig_root:
            # write headers
            for header in self.headers:
                kconfig_root.write("%s\n" % header)

            kconfig_root.write("mainmenu \"%s Configuration\"\n" % self.title)

            for source in sources:
                if self.recreate:
                    source_root_relpath = self._get_root_relpath(source)
                    source_arg = self._get_srctree_relpath(source_root_relpath)
                else:
                    source_arg = source

                self.logger.debug(f"source: {source} -> {source_arg}")
                kconfig_root.write(f"source \"{source_arg}\"\n")
                self._parse_kconfig(None, source)

        if self.list_sources:
            for apath, rpath in self.kconfig_sources.items(): print(f"{apath}")

    def summary(self):
        self.logger.info("Imported %d kconfig sources" % len(self.kconfig_sources))
        for source, relpath in self.kconfig_sources.items():
            self.logger.info(f"  {source} : {relpath}")
        self.logger.info("Generator Kconfig at %s" % self.kconfig_root)

def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter, description=__doc__)

    parser.add_argument("-s", "--silent", action='store_true', help="suppress all log output")
    parser.add_argument("-l", "--list-sources", action='store_true', help="list all kconfig sources")
    parser.add_argument("--kconfig", required=True, help="path for output file for project Kconfig")
    parser.add_argument("--title", required=True, help="Project Title")
    parser.add_argument("--sources", nargs='+', help="Paths to kconfig for projects")

    args = parser.parse_args()

    if not args.silent:
        logging.basicConfig(level=logging.DEBUG)

    # convert all sources to absolute and check if it exists
    kconfig_sources = []
    for source in args.sources:
        if not os.path.isabs(source):
            source = os.path.abspath(source)

        if not os.path.exists(source):
            raise Exception("Could not find file: %s" % source)
        elif not os.path.isfile(source):
            raise Exception("Not a file: %s" % source)
        kconfig_sources.append(Path(source))

    kconfig_root = os.path.abspath(args.kconfig)
    srctree = os.getenv("srctree", os.getcwd())

    kconfig = KconfigMerge(title=args.title,
                           kconfig_root=kconfig_root,
                           list_sources=args.list_sources,
                           srctree=srctree)
    kconfig.import_sources(kconfig_sources)
    kconfig.summary()

if __name__ == "__main__":
    main()

