#!/usr/bin/env python3

# Copyright (c) 2022, Cedric Velandres
# SPDX-License-Identifier: MIT

"""
Generate root kconfig that links all specified kconfig files
"""

KCONFIG_ROOT_HEADER="# AUTOGENERATED FILE. DO NOT MODIFY "
KCONFIG_DEFAULT_MAINMENU="Kconfig Project Configuration"

import argparse
import logging
import re
import os

class KconfigMerge:
    def __init__(self, title: str,
                 kconfig_root: str,
                 srctree: str = "", 
                 overwrite = 'always',
                 recreate: bool = False,
                 list_sources: bool = True) -> None:
        self.title = title
        self.kconfig_root = kconfig_root
        self.sources = []
        self.parent_dir = os.path.dirname(kconfig_root)
        self.common_dir = srctree
        self.overwrite = overwrite
        self.kconfig_sources = {}
        self.logger = logging.getLogger("KconfigMerge")
        self.headers = ["# AUTOGENERATED FILE. DO NOT MODIFY"]
        self.recreate = recreate
        self.list_sources = list_sources

        self.logger.debug(f"parent_dir: {self.parent_dir}")
        self.logger.debug(f"common_dir: {self.common_dir}")

        # precreate parent dir
        os.makedirs(self.parent_dir, exist_ok=True)

        pass

    def _get_source_relpath(self, source_path: str) -> str:
        """
        Returns the relative source path of input path with respect to common path of all sources
        """
        return os.path.relpath(source_path, self.common_dir)

    def _get_parent_relpath(self, source_path: str) -> str:
        """
        Returns the relative source path of input path with respect to parent path of output kconfig root
        Also creates directories for the path
        """
        parent_relpath = os.path.join(self.parent_dir, self._get_source_relpath(source_path))
        os.makedirs(os.path.dirname(parent_relpath), exist_ok=True)
        return parent_relpath

    def _parse_kconfig(self, kconfig_source: str) -> list:
        kconfig_source_relpath = self._get_source_relpath(kconfig_source)
        kconfig_parent_relpath = self._get_parent_relpath(kconfig_source)
        kconfig_source_dirname = os.path.dirname(kconfig_source)
        rsource_parent = os.path.dirname(kconfig_source_relpath)

        if self.list_sources:
            print(f"{os.path.abspath(kconfig_source)}")

        self.logger.debug(f"rsource_parent:  {rsource_parent}")
        self.logger.debug(f"source_relpath:  {kconfig_source_relpath}")
        self.logger.debug(f"parent_relpath:  {kconfig_parent_relpath}")
        self.logger.debug(f"source_dirname:   {kconfig_source_dirname}")

        # store parsed kconfig sources and destination kconfig file
        self.kconfig_sources[kconfig_source] = kconfig_parent_relpath

        self.logger.debug("\tParsing %s", kconfig_source_relpath)
        with open(kconfig_source, 'r') as f_source:
            if self.recreate: f_source_out = open(kconfig_parent_relpath, 'w')
            for f_source_line in f_source:
                match = re.match(r"^([r]?source)\s*\"([^\"]*)\"", f_source_line)
                if match:
                    source_token = match.group(1)
                    source_dir = match.group(2)

                    source_abspath = os.path.join(kconfig_source_dirname, source_dir)
                    source_relpath = self._parse_kconfig(source_abspath)

                    if self.recreate:
                        if source_token == "rsource":
                            # remake it relative to current dir
                            source_relpath = os.path.relpath(source_relpath, rsource_parent)
                        elif source_token == "source":
                            pass
                        else:
                            raise ValueError(f"Unsupported token: {source_token}")

                        self.logger.debug(f"\t{source_token}: {source_abspath} -> {source_relpath}")
                        f_source_out.write(f"{source_token} \"%s\"\n" % source_relpath)

                else:
                    if self.recreate:
                        f_source_out.write(f_source_line)
            if self.recreate: f_source_out.close()

        return kconfig_source_relpath

    def import_sources(self, sources: list):
        """
        Imports a set of kconfig files to generate a tree of kconfig with adjusted
        source paths wre to the common dir of all kconfig paths
        """
        if(len(sources) > 1):
            self.common_dir = os.path.commonpath(sources)
        else:
            # This really isn't a nice way to to do this :(
            self.common_dir = os.path.abspath(os.path.dirname(os.path.join(sources[0], "../../..")))

        with open(self.kconfig_root, 'w') as kconfig_root:
            # write headers
            for header in self.headers:
                kconfig_root.write("%s\n" % header)

            kconfig_root.write("mainmenu \"%s Configuration\"\n" % self.title)

            for source in sources:
                # parse kconfig file to search for nested sources
                # and update source paths to parent dir
                source_path = self._parse_kconfig(source)
                if not self.recreate:
                    self.kconfig_sources[source] = self._get_parent_relpath(source)
                    source_path = os.path.abspath(source)
                self.logger.debug(f"source: {source} -> {source_path}")
                kconfig_root.write("source \"%s\"\n" % source_path)
                pass
        pass

    def summary(self):
        self.logger.info("Imported %d kconfig sources" % len(self.kconfig_sources))
        for source, relpath in self.kconfig_sources.items():
            self.logger.info(f"  {source} : {relpath}")
        self.logger.info("Generator Kconfig at %s" % self.kconfig_root)

def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter, description=__doc__)

    parser.add_argument("-s", "--silent", action='store_true', help="suppress all log output")
    parser.add_argument("-l", "--list-sources", action='store_true', help="list all kconfig sources")
    parser.add_argument("--kconfig", required=True, help="path for output file for project Kconfig")
    parser.add_argument("--title", required=True, help="Project Title")
    parser.add_argument("--sources", nargs='+', help="Paths to kconfig for projects")
    parser.add_argument("--recreate", action='store_true', help="Recreates the kconfig source directory. Useful when 'rsource' is not supported")

    args = parser.parse_args()

    if not args.silent:
        logging.basicConfig(level=logging.DEBUG)

    # convert all sources to absolute and check if it exists
    kconfig_sources = []
    for source in args.sources:
        if not os.path.isabs(source):
            source = os.path.abspath(source)

        if not os.path.exists(source):
            raise Exception("Could not find file: %s" % source)
        elif not os.path.isfile(source):
            raise Exception("Not a file: %s" % source)
        kconfig_sources.append(source)

    kconfig_root = os.path.abspath(args.kconfig)

    kconfig = KconfigMerge(title=args.title,
                           kconfig_root=kconfig_root,
                           recreate=args.recreate)
    kconfig.import_sources(kconfig_sources)
    kconfig.summary()

if __name__ == "__main__":
    main()

